[package]
name = "wenpan-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
lazy_static = "1.4.0"

[[example]]
name = "deadlock"
path = "examples/static_deadlock.rs"