[package]
name = "conditional_compilation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["public"]
public = []
feature_1 = []
feature_2 = []
